export const FetchingDashboardData_InProgress="FetchingDashboardData_InProgress"
export const FetchingDashboardData_Success="FetchingDashboardData_Success"
export const FetchingDashboardData_Fail="FetchingDashboardData_Fail"
export const FetchingBuildingNames_Success="FetchingBuildingNames_Success"

export const FetchingApartmentNames_InProgress="FetchingApartmentNames_InProgress"
export const FetchingApartmentNames_Success="FetchingApartmentNames_Success"
export const FetchingApartmentNames_Fail="FetchingApartmentNames_Fail"
