export const fetchingProjectDetails_InProgress="fetchingProjectDetails_InProgress"
export const fetchingProjectDetails_Success="fetchingProjectDetails_Success"
export const fetchingProjectDetails_Fail="fetchingProjectDetails_Fail"

export const fetchingOrganizationNames_InProgress="fetchingOrganizationNames_InProgress"
export const fetchingOrganizationNames_Success="fetchingOrganizationNames_Success"
export const setProjectDetailsSucessToFalse="setProjectDetailsSucessToFalse"

export const setServiceList_SuperAdmin="setServiceList_SuperAdmin"
export const fetchingProjectDetails_GeenralUser_Success="fetchingProjectDetails_GeenralUser_Success"
export const fetchingProjectDetails_GeneralUser_InProgress="fetchingProjectDetails_GeneralUser_InProgress"
export const fetchingOrganizationNames_GeneralUser_Success="fetchingOrganizationNames_GeneralUser_Success"

export const updateProjectDetails_InProgress="updateProjectDetails_InProgress"
export const updateProjectDetails_Success="updateProjectDetails_Success"
export const updateProjectDetails_Fail="updateProjectDetails_Fail"

export const deletingProjectAdmin_InProgress="deletingProjectAdmin_InProgress"
export const deletingProjectAdmin_Success="deletingProjectAdmin_Success"
export const deletingProjectAdmin_Fail="deletingProjectAdmin_InProgress"

export const deleteProject_InProgress="deleteProject_InProgress"
export const deleteProject_Success="deleteProject_Success"
export const deleteProject_Fail="deleteProject_Fail"

export const addProjectAdmin_InProgress="addProjectAdmin_InProgress"
export const addProjectAdmin_Success="addProjectAdmin_Success"
export const addProjectAdmin_Fail="addProjectAdmin_InProgress"
export const addProjectAdmin_Duplicacy="addProjectAdmin_Duplicacy"

export const createProject_Duplicacy="createProject_Duplicacy"

export const updatingProjectServiceDetails="updatingProjectServiceDetails"
export const updateProjectServiceDetailsSuccess="updateProjectServiceDetailsSuccess"
export const updateProjectServiceDetailsFail="updateProjectServiceDetailsFail"


export const fetchingProjectUnassignedServices="fetchingProjectUnassignedServices"
export const ProjectUnassignedServicesFetchSuccess="ProjectUnassignedServicesFetchSuccess"
export const ProjectUnassignedServicesFetch_Fail="ProjectUnassignedServicesFetch_Fail"


export const assignServiceInProjectSave_InProgress="assignServiceInProjectSave_InProgress"
export const assignServiceInProjectSave_Success="assignServiceInProjectSave_Success"
export const assignServiceInProjectSave_Fail="assignServiceInProjectSave_Fail"


export const createProject_InProgress="createProject_InProgress"
export const createProject_Success="createProject_Success"
export const createProject_Fail="createProject_Fail"


export const setProjectNameDuplicacyToNull="setProjectNameDuplicacyToNull"